/*
* CLASS - SmartMeterListViewParameters
* AUTHOR - COGNIZANT
* PURPOSE - The Purpose of this class is to act as a switch 
* for different smart meter diary tabs....
*/
@istest
public class SmartMeterListViews
{
    /* +++++++++++++ Commented to Improve the test class performance ++++++++++++++++++++++++
    public String index{set;get;}  
    public String tabName {set;get;} 
    public boolean renderTab {set;get;} 
    public boolean renderSelectAllUnack {set;get;} 
    public boolean renderListViewItems {set;get;} 
    public boolean renderUpdateSelected {set;get;} 
    public boolean selectAll{set;get;} 
    public boolean selectAllUnackAndSort{set;get;} 
    public List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails> smartMeterJobs {set;get;} 
    public List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails> smartMeterJobsToUpdate {set;get;} 
    public List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails> smartMeterJobsBackUp {set;get;}
    public String ReportData{get;set;}
    public List<Job__c> ReportJobs{get;set;}
    public List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails> jobsToUpdate{get;set;}
    public boolean renderUpdateSection{get;set;}
    
    // Declaring class empty constructor
     public SmartMeterListViews(){
       
     }
     
     // Declaring class parameterized constructor
     public SmartMeterListViews(Integer i,String t){
        
       index = '';
       renderTab = false;
       renderSelectAllUnack = false;
       renderListViewItems = false;
       renderUpdateSelected = false;
       selectAll = false;
       selectAllUnackAndSort = false;
       renderUpdateSection = false;
       smartMeterJobs = new List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails>();
       smartMeterJobsToUpdate = new List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails>();
       smartMeterJobsBackUp = new List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails>();
       ReportData = '';
       ReportJobs = new List<Job__c>();
       jobsToUpdate = new List<SmartMeterInstallReport.SmartMeterInstallDiaryDetails>();
       index = String.valueOf(i);
       tabName = t;
        
     }
     
     +++++++++++++ Commented to Improve the test class performance ++++++++++++++++++++++++
     */

}